#!/bin/bash
# =============================================================================
# Docker entrypoint for openSIS on Railway
# Writes database config from environment variables,
# runs the billing schema if not already installed,
# then starts Apache.
# =============================================================================

set -e

export APP_DIR="/var/www/html"

echo "▶ Starting openSIS entrypoint..."

# ── 1. Map Railway MySQL env vars → internal names ────────────────────────────
# Railway's MySQL plugin injects MYSQLHOST, MYSQLUSER, MYSQLPASSWORD, etc.
# Fall back to DB_* for manual overrides.
DB_HOST="${MYSQLHOST:-${DB_HOST:-}}"
DB_PORT="${MYSQLPORT:-${DB_PORT:-3306}}"
DB_NAME="${MYSQLDATABASE:-${DB_NAME:-railway}}"
DB_USER="${MYSQLUSER:-${DB_USER:-}}"
DB_PASS="${MYSQLPASSWORD:-${DB_PASS:-}}"
APP_URL="${APP_URL:-http://localhost}"

# ── 2. Validate required environment variables ────────────────────────────────
for VAR in DB_HOST DB_NAME DB_USER DB_PASS; do
  if [ -z "${!VAR}" ]; then
    echo "ERROR: Could not resolve $VAR. Set MYSQL* vars via Railway MySQL service or DB_* manually."
    exit 1
  fi
done

# ── 3. Write openSIS database config file ─────────────────────────────────────
echo "▶ Writing database configuration..."
cat > "$APP_DIR/DatabaseInc.php" <<EOF
<?php
/**
 * openSIS Database Configuration
 * Auto-generated by docker-entrypoint.sh from environment variables.
 * Do not edit manually — update Railway environment variables instead.
 */

\$DatabaseServer   = '${DB_HOST}';
\$DatabasePort     = '${DB_PORT}';
\$DatabaseName     = '${DB_NAME}';
\$DatabaseUsername = '${DB_USER}';
\$DatabasePassword = '${DB_PASS}';

// PDO connection used by billing module
define('DB_HOST', '${DB_HOST}');
define('DB_PORT', '${DB_PORT}');
define('DB_NAME', '${DB_NAME}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');
EOF
echo "  ✓ DatabaseInc.php written"

# ── 4. Wait for MySQL to be ready (PHP/mysqli — works with MySQL 9.x caching_sha2_password) ──
echo "▶ Waiting for MySQL at ${DB_HOST}:${DB_PORT}..."
php -r "
\$host = getenv('DB_HOST');
\$port = (int) getenv('DB_PORT');
\$user = getenv('DB_USER');
\$pass = getenv('DB_PASS');
\$name = getenv('DB_NAME');
\$max  = 60;
for (\$i = 1; \$i <= \$max; \$i++) {
    \$m = @new mysqli(\$host, \$user, \$pass, \$name, \$port);
    if (\$m->connect_errno === 0) {
        \$m->close();
        echo \"  ✓ MySQL is ready (attempt \$i)\n\";
        exit(0);
    }
    echo \"  Attempt \$i/\$max — \" . \$m->connect_error . \" — waiting 3s...\n\";
    sleep(3);
}
echo \"ERROR: Could not connect to MySQL after \$max attempts.\n\";
exit(1);
" || exit 1

# ── 5. Install openSIS core schema + billing schema if not already present ────
echo "▶ Checking database schemas..."
php -r "
function run_sql_file(\$m, \$path) {
    \$sql = file_get_contents(\$path);
    if (\$sql === false) { echo \"ERROR: Cannot read \$path\n\"; exit(1); }
    // Detect DELIMITER \$\$ pattern (used in procs/triggers)
    if (strpos(\$sql, 'DELIMITER') !== false) {
        // Split on \$\$ delimiter, strip DELIMITER lines, run each block
        \$blocks = preg_split('/DELIMITER\s+\\\$\\\$\s*/i', \$sql);
        foreach (\$blocks as \$block) {
            foreach (array_filter(array_map('trim', explode('\$\$', \$block))) as \$stmt) {
                \$stmt = trim(preg_replace('/DELIMITER\s+;.*$/mi', '', \$stmt));
                if (\$stmt === '' || preg_match('/^(--|#)/', \$stmt)) continue;
                if (!\$m->query(\$stmt)) { echo 'ERROR in ' . basename(\$path) . ': ' . \$m->error . \"\n\"; exit(1); }
            }
        }
    } else {
        // Plain semicolon-delimited SQL
        foreach (array_filter(array_map('trim', explode(';', \$sql))) as \$stmt) {
            if (preg_match('/^(--|#)/i', \$stmt)) continue;
            if (!\$m->query(\$stmt)) { echo 'ERROR in ' . basename(\$path) . ': ' . \$m->error . \"\n\"; exit(1); }
        }
    }
}

\$host   = getenv('DB_HOST');
\$port   = (int) getenv('DB_PORT');
\$user   = getenv('DB_USER');
\$pass   = getenv('DB_PASS');
\$name   = getenv('DB_NAME');
\$app    = getenv('APP_DIR');

\$m = new mysqli(\$host, \$user, \$pass, \$name, \$port);
if (\$m->connect_errno) { echo 'ERROR: ' . \$m->connect_error . \"\n\"; exit(1); }

// Check if core openSIS schema exists (app table is created by the installer)
\$row = \$m->query(\"SELECT COUNT(*) AS c FROM information_schema.tables
    WHERE table_schema='\$name' AND table_name='app'\")->fetch_assoc();

if ((int)\$row['c'] === 0) {
    echo \"  Core schema not found — running OpensisSchemaMysqlInc.sql...\n\";
    run_sql_file(\$m, \"\$app/install/OpensisSchemaMysqlInc.sql\");
    echo \"  ✓ Core schema installed\n\";
    // Seed stored procedures and triggers
    foreach (['OpensisProcsMysqlInc.sql', 'OpensisTriggerMysqlInc.sql'] as \$f) {
        \$path = \"\$app/install/\$f\";
        if (file_exists(\$path)) { run_sql_file(\$m, \$path); echo \"  ✓ \$f done\n\"; }
    }
} else {
    echo \"  ✓ Core schema already present — skipping\n\";
}

// Check billing schema
\$row = \$m->query(\"SELECT COUNT(*) AS c FROM information_schema.tables
    WHERE table_schema='\$name' AND table_name='billing_fee_types'\")->fetch_assoc();

if ((int)\$row['c'] === 0) {
    echo \"  Running billing_schema.sql...\n\";
    run_sql_file(\$m, \"\$app/install/billing_schema.sql\");
    echo \"  ✓ Billing schema installed\n\";
} else {
    echo \"  ✓ Billing schema already present — skipping\n\";
}
\$m->close();
" || exit 1

# ── 6. Configure Apache to use Railway's $PORT ────────────────────────────────
APACHE_PORT="${PORT:-80}"
echo "▶ Configuring Apache on port ${APACHE_PORT}..."

cat > /etc/apache2/ports.conf <<EOF
Listen ${APACHE_PORT}
EOF

cat > /etc/apache2/sites-enabled/000-default.conf <<EOF
<VirtualHost *:${APACHE_PORT}>
    ServerName localhost
    DocumentRoot /var/www/html

    <Directory /var/www/html>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog \${APACHE_LOG_DIR}/error.log
    CustomLog \${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
EOF

echo "  ✓ Apache configured on port ${APACHE_PORT}"

# ── 7. Set correct permissions ────────────────────────────────────────────────
chown -R www-data:www-data /var/www/html/assets 2>/dev/null || true
chmod -R 775 /var/www/html/assets 2>/dev/null || true

# Ensure only mpm_prefork is active (runtime safety net)
rm -f /etc/apache2/mods-enabled/mpm_event.* /etc/apache2/mods-enabled/mpm_worker.* 2>/dev/null || true

echo "▶ Starting Apache..."
exec "$@"
