#!/bin/bash
# =============================================================================
# Docker entrypoint for openSIS on Railway
# Writes database config from environment variables,
# runs the billing schema if not already installed,
# then starts Apache.
# =============================================================================

set -e

APP_DIR="/var/www/html"

echo "▶ Starting openSIS entrypoint..."

# ── 1. Map Railway MySQL env vars → internal names ────────────────────────────
# Railway's MySQL plugin injects MYSQLHOST, MYSQLUSER, MYSQLPASSWORD, etc.
# Fall back to DB_* for manual overrides.
DB_HOST="${MYSQLHOST:-${DB_HOST:-}}"
DB_PORT="${MYSQLPORT:-${DB_PORT:-3306}}"
DB_NAME="${MYSQLDATABASE:-${DB_NAME:-railway}}"
DB_USER="${MYSQLUSER:-${DB_USER:-}}"
DB_PASS="${MYSQLPASSWORD:-${DB_PASS:-}}"
APP_URL="${APP_URL:-http://localhost}"

# ── 2. Validate required environment variables ────────────────────────────────
for VAR in DB_HOST DB_NAME DB_USER DB_PASS; do
  if [ -z "${!VAR}" ]; then
    echo "ERROR: Could not resolve $VAR. Set MYSQL* vars via Railway MySQL service or DB_* manually."
    exit 1
  fi
done

# ── 3. Write openSIS database config file ─────────────────────────────────────
echo "▶ Writing database configuration..."
cat > "$APP_DIR/DatabaseInc.php" <<EOF
<?php
/**
 * openSIS Database Configuration
 * Auto-generated by docker-entrypoint.sh from environment variables.
 * Do not edit manually — update Railway environment variables instead.
 */

\$DatabaseServer   = '${DB_HOST}';
\$DatabasePort     = '${DB_PORT}';
\$DatabaseName     = '${DB_NAME}';
\$DatabaseUsername = '${DB_USER}';
\$DatabasePassword = '${DB_PASS}';

// PDO connection used by billing module
define('DB_HOST', '${DB_HOST}');
define('DB_PORT', '${DB_PORT}');
define('DB_NAME', '${DB_NAME}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');
EOF
echo "  ✓ DatabaseInc.php written"

# ── 4. Wait for MySQL to be ready ─────────────────────────────────────────────
echo "▶ Waiting for MySQL at ${DB_HOST}:${DB_PORT}..."
MAX_TRIES=60
COUNT=0
until mysql -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASS" -e "SELECT 1;" "$DB_NAME" >/dev/null 2>&1; do
  COUNT=$((COUNT + 1))
  if [ $COUNT -ge $MAX_TRIES ]; then
    echo "ERROR: Could not connect to MySQL after ${MAX_TRIES} attempts. Check DB_* variables."
    exit 1
  fi
  echo "  Attempt $COUNT/$MAX_TRIES — waiting 3s..."
  sleep 3
done
echo "  ✓ MySQL is ready"

# ── 5. Run billing schema if not already installed ────────────────────────────
echo "▶ Checking billing schema..."
TABLE_EXISTS=$(mysql -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASS" "$DB_NAME" \
  -se "SELECT COUNT(*) FROM information_schema.tables
       WHERE table_schema='${DB_NAME}' AND table_name='billing_fee_types';" 2>/dev/null || echo "0")

if [ "$TABLE_EXISTS" = "0" ]; then
  echo "  Running billing_schema.sql..."
  mysql -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASS" "$DB_NAME" \
    < "$APP_DIR/install/billing_schema.sql"
  echo "  ✓ Billing schema installed"
else
  echo "  ✓ Billing schema already present — skipping"
fi

# ── 6. Configure Apache to use Railway's $PORT ────────────────────────────────
APACHE_PORT="${PORT:-80}"
echo "▶ Configuring Apache on port ${APACHE_PORT}..."

cat > /etc/apache2/ports.conf <<EOF
Listen ${APACHE_PORT}
EOF

cat > /etc/apache2/sites-enabled/000-default.conf <<EOF
<VirtualHost *:${APACHE_PORT}>
    ServerName localhost
    DocumentRoot /var/www/html

    <Directory /var/www/html>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog \${APACHE_LOG_DIR}/error.log
    CustomLog \${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
EOF

echo "  ✓ Apache configured on port ${APACHE_PORT}"

# ── 7. Set correct permissions ────────────────────────────────────────────────
chown -R www-data:www-data /var/www/html/assets 2>/dev/null || true
chmod -R 775 /var/www/html/assets 2>/dev/null || true

echo "▶ Starting Apache..."
exec "$@"
